version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mae3user
      POSTGRES_PASSWORD: supersecurepw
      POSTGRES_DB: mae3
      TZ: Asia/Seoul
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data