version: "3"
services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

  server:
    image: <your-ecr-uri>/nest-serverservices:
  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-server
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - redis
      - qdrant
:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - redis
      - qdrant
