version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    restart: always
    ports:
      - "6333:6333"    # HTTP API 포트
      - "6334:6334"    # gRPC 포트
    volumes:
      - ./qdrant_data:/qdrant/storage