version: "3"
services:
  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./qdrant_data:/qdrant/storage

# #로컬용
#   server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     container_name: nest-server
#     restart: always
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./server/.env
#     environment:
#       - TZ=Asia/Seoul
#     depends_on:
#       - redis
#       - qdrant

#서버용
  server:
    image: 123403344015.dkr.ecr.ap-northeast-2.amazonaws.com/dailyexpression:latest
    container_name: nest-server
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
      - qdrant