services:
  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./redis_data:/data
      - ./redis_conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./qdrant_data:/qdrant/storage      

#모니터링 대시보드 서비스 추가
  bull-board:
    build:
      context: ./bull-board 
      dockerfile: Dockerfile
    container_name: bull-board-dashboard
    restart: always
    ports:
      - "4000:4000" 
    env_file:
      - ./server/.env
    environment:
      - TZ=Asia/Seoul
      # REDIS_URL은 Dockerfile.arena 내부에서 설정되거나 .env 파일로 주입됩니다.
    depends_on:
      - redis # Redis 서비스에 의존성 추가

# #서버용
#   server:
#     image: 123403344015.dkr.ecr.ap-northeast-2.amazonaws.com/dailyexpression:latest
#     container_name: nest-server
#     restart: always
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./server/.env
#     environment:
#       - TZ=Asia/Seoul
#     depends_on:
#       - redis
#       - qdrant

#################################################################################
# 로컬용
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-server
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - redis
      - qdrant

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    restart: always
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
      - TZ=Asia/Seoul

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    restart: always
    environment:
      # 보내주신 RDS 정보로 생성한 연결 문자열입니다.
      - DATA_SOURCE_NAME=postgresql://postgres:dkdldnjs7098@database-1.c9c0wa4we8a7.ap-northeast-2.rds.amazonaws.com:5432/daily_three_expression?sslmode=require
    ports:
      - "9187:9187"

  mail-worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mail-worker
    restart: always
    depends_on:
      - redis
    env_file:
      - ./server/.env
    environment:
      - TZ=Asia/Seoul
    command: node -r tsconfig-paths/register dist/mailer/worker/email.worker.js


volumes:
  grafana-storage:
