port 26379


# 마스터 모니터링 설정
# sentinel monitor <마스터그룹이름> <마스터IP> <마스터Port> <쿼럼수>
# <마스터IP>는 docker-compose의 서비스 이름(redis-master)을 사용합니다.
# 쿼럼(Quorum)은 마스터의 장애를 판단하기 위한 최소 센티넬 동의 수입니다. (총 3대 중 2대 동의)
sentinel monitor mymaster redis-master 6379 2

# 마스터가 다운되었다고 판단하는 시간 (5초)
sentinel down-after-milliseconds mymaster 5000

# 장애 조치(Failover) 타임아웃 시간 (10초)
sentinel failover-timeout mymaster 10000

# 한 번에 동기화할 슬레이브 수
sentinel parallel-syncs mymaster 1